; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- N16R8 Hardware Configurations ---
board_build.arduino.memory_type = qio_opi ; Configures Octal PSRAM (R8) and QIO Flash
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv ; Gives you 2x 3MB App slots for OTA + large storage
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1 ; Directs Serial output to the native USB port
   

; --- OPTION A: USB Uploading (Uncomment this section when using a cable) ---
;upload_protocol = esptool

; ; --- OPTION B: Wireless OTA Uploading (Uncomment this section to flash over Wi-Fi) ---
upload_protocol = espota
upload_port = 10.47.0.3     ; Put your ESP32's actual IP address here
upload_flags =
    --auth=admin
    --host_port=8266            ; Matches the ArduinoOTA.setPassword("admin") in your code


